### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-aircall

on:
  pull_request:
  push:
    branches: master
jobs:
  linting:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # Only lint using the primary version used for dev
        python-version: ["3.8.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
    - name: Install dependencies
      run: |
        poetry install
    - name: Run lint command from tox.ini
      run: |
        poetry run tox -e lint
